### PR TITLE
change collapsible bar style

### PR DESCRIPTION
**Pull request by SebasDuranona**
I decided to get rid of the home button in the navBar and just include it in the actual collapsible menu.
I think it's more straightforward now, let me know what you guys think!

### CODE REVIEW

**Comment by Sonjya00** [comment]
I think having the diamond and the menu link close together makes it way more intuitive.
How about changing the default color of both the diamond and the menu link from black to a brighter color (white or the lightest blue from our palette)? Also, maybe it would look a bit better without using all caps for the menu link.

**Comment by SebasDuranona** [comment]
You're right, it looks much better now :D

**Review by jhuppe — APPROVED** [review]
This looks great.

**Review by Sonjya00 — APPROVED** [review]
Looks great now! Merging this

**Pull request merged**
