### PR TITLE
Fix footer position, create default styles

### PR DESCRIPTION
**Pull request by Sonjya00**
With this commit I've mostly made styles changes:
1) Fixed footer to the bottom of each pages (only the landing page always has a visible footer);
2) Created some mixins for the pages basic setup (background color, margins, line-height, etc) and for the primary headings. This way all pages have the same styles and it will be simpler to update them later;
3) Fixed some errors in the console;
4) Fixed general positioning issues;

### CODE REVIEW

**Review by jhuppe — CHANGES_REQUESTED** [review]
The footer looks fine on the landing page and the about page, but on all of the others it is floating at the end of the content which doesn't span the whole page. 
2019-04-15_11h05_22

**Comment by Sonjya00** [comment]
The footer position was fine for me in both the About and the Stories pages. I think it's because in the other pages there isn't as much content. Anyways, it should be fixed now.

**Review by jhuppe — APPROVED** [review]
Looks good.

**Review by SebasDuranona — APPROVED** [review]
Looks good!

**Pull request merged**
