### PR TITLE
Basic a11y, footer fix, content shift, styles changes

### PR DESCRIPTION
**Pull request by Sonjya00**
1) Added basic accessibility;
2) Fixed a problem with a footer in the landing page;
3) Moved the "Services" list from the About page to the Donate page;
4) Some styles fixes

### CODE REVIEW

**Review by jhuppe — APPROVED** [review]
I think that all of the changes look really good. I don't know why, but when I run your branch the previous changes that we merged into master don't appear to be in your branch (i.e. additional photos on photo page, responsive styling of about page, ect).

**Comment by Sonjya00** [comment]
I realized my branch was not updated but I figured out how to include the previous changes. Now everything should be there

**Comment by jhuppe** [comment]
This looks good now. I like the horizontal rule below the page title.

**Comment by SebasDuranona** [comment]
Nice!
I'll merge it!

**Review by SebasDuranona — APPROVED** [review]

**Pull request merged**
